side = eval(input("Enter the side of star : "))

import turtle
turtle.penup()
turtle.goto(-side/2,0)
turtle.pendown()
turtle.forward(side)
turtle.right(144)
turtle.forward(side)
turtle.right(144)
turtle.forward(side)
turtle.right(144)
turtle.forward(side)
turtle.right(144)
turtle.forward(side)
turtle.right(144)
turtle.done()