import math 
import turtle
x1,y1 = eval(input("Enter the first point p1 (x1,y1):"))
x2,y2 = eval(input("Enter the first point p2 (x2,y2):"))
x3,y3 = eval(input("Enter the first point p3 (x3,y3):"))
a=math.sqrt((x1-x2)**2+(y1-y2)**2)
b=math.sqrt((x1-x3)**2+(y1-y3)**2)
c=math.sqrt((x3-x2)**2+(y3-y2)**2)
A=int(math.degrees(math.acos((a*a-b*b-c*c)/(-2*b*c))))
B=int(math.degrees(math.acos((b*b-a*a-c*c)/(-2*a*c))))
C=int(math.degrees(math.acos((c*c-b*b-a*a)/(-2*b*c))))
turtle.penup()
turtle.goto(x1,y1)
turtle.pendown()
turtle.write("("+str(x1)+","+str(y1)+")\n"+str(A)+"degsree")
turtle.penup()
turtle.goto(x1,y1)
turtle.pendown()
turtle.goto(x2,y2)
turtle.write("("+str(x2)+","+str(y2)+")\n"+str(B)+"degsree")
turtle.penup()
turtle.goto(x2,y2)
turtle.pendown()
turtle.goto(x3,y3)
turtle.write("("+str(x3)+","+str(y3)+")\n"+str(C)+"degsree")
turtle.goto(x1,y1)
turtle.penup()
turtle.goto(-75,-75)
turtle.pendown()
turtle.done()
